-- CreateTable
CREATE TABLE "auth_config" (
    "id" TEXT NOT NULL,
    "enablePhoneRegistration" BOOLEAN NOT NULL DEFAULT true,
    "phoneRequired" BOOLEAN NOT NULL DEFAULT true,
    "phoneVerificationRequired" BOOLEAN NOT NULL DEFAULT false,
    "enableEmailRegistration" BOOLEAN NOT NULL DEFAULT false,
    "emailRequired" BOOLEAN NOT NULL DEFAULT false,
    "emailVerificationRequired" BOOLEAN NOT NULL DEFAULT false,
    "enableGoogleLogin" BOOLEAN NOT NULL DEFAULT false,
    "googleClientId" TEXT,
    "googleClientSecret" TEXT,
    "googleAndroidClientId" TEXT,
    "googleIosClientId" TEXT,
    "enableAppleLogin" BOOLEAN NOT NULL DEFAULT false,
    "appleClientId" TEXT,
    "appleTeamId" TEXT,
    "appleKeyId" TEXT,
    "applePrivateKey" TEXT,
    "enableFacebookLogin" BOOLEAN NOT NULL DEFAULT false,
    "facebookAppId" TEXT,
    "facebookAppSecret" TEXT,
    "enableDirectLogin" BOOLEAN NOT NULL DEFAULT true,
    "enableOtpLogin" BOOLEAN NOT NULL DEFAULT false,
    "otpExpirationMinutes" INTEGER NOT NULL DEFAULT 5,
    "otpLength" INTEGER NOT NULL DEFAULT 6,
    "maxOtpAttempts" INTEGER NOT NULL DEFAULT 5,
    "otpLockoutMinutes" INTEGER NOT NULL DEFAULT 30,
    "minPasswordLength" INTEGER NOT NULL DEFAULT 8,
    "requireUppercase" BOOLEAN NOT NULL DEFAULT true,
    "requireLowercase" BOOLEAN NOT NULL DEFAULT true,
    "requireNumbers" BOOLEAN NOT NULL DEFAULT true,
    "requireSpecialChars" BOOLEAN NOT NULL DEFAULT false,
    "accessTokenExpirationMins" INTEGER NOT NULL DEFAULT 15,
    "refreshTokenExpirationDays" INTEGER NOT NULL DEFAULT 7,
    "maxActiveSessions" INTEGER NOT NULL DEFAULT 5,
    "enableTwoFactor" BOOLEAN NOT NULL DEFAULT false,
    "enableBiometric" BOOLEAN NOT NULL DEFAULT true,
    "enableDeviceTracking" BOOLEAN NOT NULL DEFAULT true,
    "requireName" BOOLEAN NOT NULL DEFAULT true,
    "requireAvatar" BOOLEAN NOT NULL DEFAULT false,
    "defaultCountryCode" TEXT NOT NULL DEFAULT 'GLOBAL',
    "defaultCurrency" TEXT NOT NULL DEFAULT 'USD',
    "defaultLanguage" TEXT NOT NULL DEFAULT 'en',
    "termsUrl" TEXT,
    "termsUrlAr" TEXT,
    "privacyUrl" TEXT,
    "privacyUrlAr" TEXT,
    "requireTermsAcceptance" BOOLEAN NOT NULL DEFAULT true,
    "loginScreenTitle" TEXT NOT NULL DEFAULT 'Welcome Back',
    "loginScreenTitleAr" TEXT NOT NULL DEFAULT 'مرحباً بعودتك',
    "registerScreenTitle" TEXT NOT NULL DEFAULT 'Create Account',
    "registerScreenTitleAr" TEXT NOT NULL DEFAULT 'إنشاء حساب',
    "loginBackgroundUrl" TEXT,
    "registerBackgroundUrl" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "updatedBy" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auth_config_pkey" PRIMARY KEY ("id")
);
