workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.usdtwallet.app"
      node: 22
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          cd apps/web
          npm run build
      - name: Sync Capacitor
        script: |
          cd apps/web
          npx cap sync android
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > apps/web/android/local.properties
      - name: Build Android APK
        script: |
          cd apps/web/android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - apps/web/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
